### ISSUE TITLE
Feature: User can add notes to an image

### ISSUE THREAD

**Issue by salgarcia666** [salgarcia666/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can add notes to the images
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user will be able to add notes after clicking a button

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (252)](https://user-images.githubusercontent.com/51901536/134592797-cc89b702-6a70-44a6-b153-52e3e9d3c9bf.png)
![Screenshot (251)](https://user-images.githubusercontent.com/51901536/134592799-16cf24c7-fae2-435b-89e6-f302c7995abd.png)

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure that click targets is a `<button>` element.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Make sure that after the button is clicked an input text box appears
- [ ] Make sure the box is in the right location
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
