### ISSUE TITLE
Feature: User can remove an image from the list

### ISSUE THREAD

**Issue by salgarcia666** [salgarcia666/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
user can remove selected images from a list of images

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user can delete images that he selects

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (256)](https://user-images.githubusercontent.com/51901536/134594604-1b988b95-41ca-4dd2-ba12-d4e0bd8996c2.png)
![Screenshot (255)](https://user-images.githubusercontent.com/51901536/134594606-187bb454-c845-4fa8-a23e-eb853ca18698.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure that click targets are <button> elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] make sure that the image is removed after clicking the remove button
- [ ] make sure that the additional info associated with the image is also removed
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
