### ISSUE TITLE
Feature: User can add the memorized images with info of breeds to a list.

### ISSUE THREAD

**Issue by salgarcia666** [salgarcia666/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user will be able to create a list of images and information related to those images and name the list whatever the want
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

you can create with a custom name with whatever images you choose so you can study it later
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (258)](https://user-images.githubusercontent.com/51901536/134600097-2169e089-2799-41a1-a984-c2e7dac9bd64.png)
![Screenshot (257)](https://user-images.githubusercontent.com/51901536/134600099-73b257bd-1569-4c8f-92f3-c04e6d828922.png)
## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] make sure there is a search bar to look for the name of your list
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
