### ISSUE TITLE
Feature: User can view random images of dogs and information about their breed.

### ISSUE THREAD

**Issue by salgarcia666** [salgarcia666/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can view a random image of a dog that is pulled from the random dog api, each time he presses a button along with information about that dogs breed
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

user will click the start button and random images of dogs will appear along with information on that dogs breed
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot (262)](https://user-images.githubusercontent.com/51901536/134601582-edc6b5f8-9626-4df1-9ba7-7b3ad57a25b9.png)
## ✅ Task List

![Screenshot (261)](https://user-images.githubusercontent.com/51901536/134601592-0f94cc3e-ca7e-45b6-afaa-c7febf331014.png)
> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] ...
- [ ] make sure that the api is working
- [ ] make sure that the images are random even after refreshing the page
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
